version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "~/phptest/:/var/www/html/"
    ports:
      - "8080:80"
  mysql-server:
    image: mysql:8.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: super03
    volumes:
      - ~/phptest/mysqldata:/var/lib/mysql
      - ~/phptest/simple.sql:/simple.sql
      - ~/phptest/advanced.sql:/advanced.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: super03
    ports:
      - "5000:80"
volumes:
  mysqldata: