version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "~/wildernessCreate/src/:/var/www/html/"
      - "~/wildernessCreate/php.ini:/usr/local/etc/php/conf.d/php.ini"
    ports:
      - "8082:80"
  mysql-server:
    image: mariadb/server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $pass
    volumes:
      - ~/wildernessCreate/mysqldata:/var/lib/mysql
      - ~/wilderness-extra:/sqlScripts
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: $pass
    ports:
      - "5000:80"
volumes:
  mysqldata:
